import "./globals.css";
import type { Metadata } from "next";
import Preloader from "@/components/preloader";
import Footer from "@/components/global/footer";
import Header from "@/components/global/header";
import { SoundProvider } from "@/context/sound-context";
import SvgOutline from "@/components/global/svg-outline";
import SmoothScroll from "@/components/global/smooth-scroll";
import GrainOverlay from "@/components/global/grain-overlay";
import CustomCursor from "@/components/global/custom-cursor";
import ImagesUnderline from "@/components/global/images-underline";
import { BackgroundMusic } from "@/components/sound/background-music";
import { Alegreya, Cinzel, Cinzel_Decorative } from "next/font/google";
import { ScrollTriggerProvider } from "@/context/scroll-trigger-context";
import { ViewTransitions } from "next-view-transitions";

const cinzelDecorative = Cinzel_Decorative({
  variable: "--font-cinzel-decorative",
  weight: ["400", "700", "900"],
  subsets: ["latin"],
});
const alegreya = Alegreya({
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-alegreya",
  subsets: ["latin"],
});
const cinzel = Cinzel({
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-cinzel",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={`${alegreya.variable} ${cinzel.variable} ${cinzelDecorative.variable} antialiased`}
        >
          <SmoothScroll>
            <SoundProvider>
              <Preloader>
                <ScrollTriggerProvider>
                  <Header />
                  <div className="min-h-screen overflow-clip relative">
                    <ImagesUnderline />
                    <BackgroundMusic />
                    <main className="min-h-screen">
                      {children}
                      <Footer />
                    </main>
                  </div>
                  {/* <CustomCursor /> */}
                </ScrollTriggerProvider>
              </Preloader>
            </SoundProvider>
            <SvgOutline />
            <GrainOverlay />
            <div id="popup-portal"></div>
          </SmoothScroll>
        </body>
      </html>
    </ViewTransitions>
  );
}
